"""Add vibe column

Revision ID: 1666276bb23d
Revises: 207d8e5c8c63
Create Date: 2025-12-27 01:37:43.564792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1666276bb23d'
down_revision: Union[str, Sequence[str], None] = '207d8e5c8c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('vibe', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'vibe')
    # ### end Alembic commands ###
